---
name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build:lib

      - name: Install current angular-datatables to demo
        working-directory: ./demo
        run: npm run link:lib

      - name: Run demo test
        working-directory: ./demo
        run: npm run demo:test-ci
