name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build:lib

      - name: Publish to NPM packages
        # includes a --ignore-scripts command argument to avoid executing npm life cycle scripts during this phase
        # for security concerns as scripts could steal NODE_AUTH_TOKEN
        run: cd dist/lib && npm publish --ignore-scripts --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

